version: '3.9'

services:
  client:
    container_name: client
    image: client
    build: 
      context: ./client/
    ports:
      - 8080:80
  server:
    container_name: server
    image: server
    build:
      context: ./server/
    ports:
      - 8081:8000
