name: Run tests for client app

on: [push, pull_request]

jobs:
  tests-client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      # Checkout the Repo
      - uses: actions/checkout@v3

      # Install Node 16
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: ./client/package.json
      - run: npm install
      # Run tests
      - run: npm test

  tests-server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      # Checkout the Repo
      - uses: actions/checkout@v3

      # Install Node 16
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: ./server/package.json
      - run: npm install
      # Run tests
      - run: npm test
