name: Run tests for client app
on: push
defaults:
  run:
    working-directory: ./client
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      # Checkout the Repo
      - uses: actions/checkout@v3

      # Install Node 16
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: ./client/package.json
      - run: npm install
      # Run tests
      - run: npm test
